Added log output on error

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -40,14 +40,26 @@ jobs:  # Определяем работы (jobs), которые будут в�
         shell: pwsh
         run: Get-ChildItem "$env:GITHUB_WORKSPACE/product-management-system" -Recurse
 
-      - name: Deploy WAR to Embedded Tomcat
+      - name: Run Application using Embedded Tomcat
         shell: pwsh
         run: |
-          Write-Output "Copying WAR file to Tomcat webapps..."
-          Copy-Item "$env:GITHUB_WORKSPACE/product-management-system/target/product-management-system-0.0.1-SNAPSHOT.war" "C:\Tomcat\webapps\product-management-system.war" -Force
-
-          Write-Output "Restarting Tomcat..."
-          Restart-Service -Name "Tomcat"
+          Write-Output "Starting application using embedded Tomcat..."
+          Start-Process -FilePath 'java' -ArgumentList '-jar', "$env:GITHUB_WORKSPACE\product-management-system\target\product-management-system-0.0.1-SNAPSHOT.war" -RedirectStandardOutput "$env:GITHUB_WORKSPACE\stdout.log" -RedirectStandardError "$env:GITHUB_WORKSPACE\stderr.log"
+          Start-Sleep -Seconds 30
+          Write-Output "Checking application status..."
+          try {
+              $response = Invoke-WebRequest -Uri "http://localhost:8080" -UseBasicParsing -TimeoutSec 10
+              if ($response.StatusCode -eq 200) {
+                Write-Output "Application is up and running."
+              } else {
+                Write-Error "Application returned status code $($response.StatusCode)."
+                exit 1
+              }
+          } catch {
+              Write-Error "Application did not start correctly."
+              exit 1
+          }
+      
 
       - name: List files in target directory
         if: always()
